# Generated by Django 4.2.11 on 2024-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='available_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
