# Generated by Django 4.2.11 on 2024-05-04 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workerprofile_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
