# Generated by Django 4.2.11 on 2024-05-04 18:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
