# Generated by Django 5.0.4 on 2024-05-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='skills_required',
        ),
    ]
